model: sctree
n_latent: 10
n_hidden: 128
encoder_arch: 'scvi'
decoder_n_layers: 0
mlp_n_layers: 1
router_n_layers: 1
router_dropout: 0.1
kl_start: 0.001
dispersion: "gene"
likelihood: "NB"
batch_correction: "global"

training:
  max_epochs: 100
  intermediate_epochs: 50
  finetuning_epochs: 50
  batch_size: 128
  lr: 0.001
  weight_decay: 0.0001
  annealing_strategy: linear
  kl_start: 0.001
  splitting_criterion: 'n_samples'
